// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yatzy.YatzyDbContext;

#nullable disable

namespace Yatzy.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20260106103509_Sum igen")]
    partial class Sumigen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yatzy.YatzyDbContext.Spiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<int>("Chance")
                        .HasColumnType("int");

                    b.Property<int>("Enere")
                        .HasColumnType("int");

                    b.Property<int>("EtPar")
                        .HasColumnType("int");

                    b.Property<int>("Femmere")
                        .HasColumnType("int");

                    b.Property<int>("FireEns")
                        .HasColumnType("int");

                    b.Property<int>("Firere")
                        .HasColumnType("int");

                    b.Property<int>("Hus")
                        .HasColumnType("int");

                    b.Property<int>("LilleStraight")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SUM")
                        .HasColumnType("int");

                    b.Property<int>("Seksere")
                        .HasColumnType("int");

                    b.Property<int>("StorStraight")
                        .HasColumnType("int");

                    b.Property<int>("ToPar")
                        .HasColumnType("int");

                    b.Property<int>("Toere")
                        .HasColumnType("int");

                    b.Property<int>("TotalSum")
                        .HasColumnType("int");

                    b.Property<int>("TreEns")
                        .HasColumnType("int");

                    b.Property<int>("Treere")
                        .HasColumnType("int");

                    b.Property<int>("Yatzy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpillerTabel");
                });
#pragma warning restore 612, 618
        }
    }
}
