// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yatzy.YatzyDbContext;

#nullable disable

namespace Yatzy.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20260121124118_upfda")]
    partial class upfda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yatzy.YatzyDbContext.ScoreBoard", b =>
                {
                    b.Property<int>("ScoreBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreBoardId"));

                    b.Property<int>("Bonus")
                        .HasColumnType("int");

                    b.Property<string>("BonusValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Chance")
                        .HasColumnType("int");

                    b.Property<int?>("Enere")
                        .HasColumnType("int");

                    b.Property<int?>("EtPar")
                        .HasColumnType("int");

                    b.Property<int?>("Femmere")
                        .HasColumnType("int");

                    b.Property<int?>("FireEns")
                        .HasColumnType("int");

                    b.Property<int?>("Firere")
                        .HasColumnType("int");

                    b.Property<int?>("Hus")
                        .HasColumnType("int");

                    b.Property<int?>("LilleStraight")
                        .HasColumnType("int");

                    b.Property<int?>("Seksere")
                        .HasColumnType("int");

                    b.Property<int?>("StorStraight")
                        .HasColumnType("int");

                    b.Property<int?>("ToPar")
                        .HasColumnType("int");

                    b.Property<int?>("Toere")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSum")
                        .HasColumnType("int");

                    b.Property<int?>("TreEns")
                        .HasColumnType("int");

                    b.Property<int?>("Treere")
                        .HasColumnType("int");

                    b.Property<int?>("Yatzy")
                        .HasColumnType("int");

                    b.HasKey("ScoreBoardId");

                    b.ToTable("ScoreBoards");
                });

            modelBuilder.Entity("Yatzy.YatzyDbContext.Spil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kasted")
                        .HasColumnType("int");

                    b.Property<int>("SpillerTurIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpilTabel");
                });

            modelBuilder.Entity("Yatzy.YatzyDbContext.Spiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spillere");
                });

            modelBuilder.Entity("Yatzy.YatzyDbContext.SpillerSpil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScoreBoardId")
                        .HasColumnType("int");

                    b.Property<int?>("SpilId")
                        .HasColumnType("int");

                    b.Property<int>("SpillerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScoreBoardId");

                    b.HasIndex("SpilId");

                    b.HasIndex("SpillerId");

                    b.ToTable("SpillerSpil");
                });

            modelBuilder.Entity("Yatzy.YatzyDbContext.Terning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiceValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsHeld")
                        .HasColumnType("bit");

                    b.Property<int?>("SpilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpilId");

                    b.ToTable("Terninger");
                });

            modelBuilder.Entity("Yatzy.YatzyDbContext.SpillerSpil", b =>
                {
                    b.HasOne("Yatzy.YatzyDbContext.ScoreBoard", "ScoreBoard")
                        .WithMany()
                        .HasForeignKey("ScoreBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yatzy.YatzyDbContext.Spil", null)
                        .WithMany("Spillere")
                        .HasForeignKey("SpilId");

                    b.HasOne("Yatzy.YatzyDbContext.Spiller", "Spiller")
                        .WithMany()
                        .HasForeignKey("SpillerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreBoard");

                    b.Navigation("Spiller");
                });

            modelBuilder.Entity("Yatzy.YatzyDbContext.Terning", b =>
                {
                    b.HasOne("Yatzy.YatzyDbContext.Spil", null)
                        .WithMany("Terninger")
                        .HasForeignKey("SpilId");
                });

            modelBuilder.Entity("Yatzy.YatzyDbContext.Spil", b =>
                {
                    b.Navigation("Spillere");

                    b.Navigation("Terninger");
                });
#pragma warning restore 612, 618
        }
    }
}
